# Reinforcement learning - dynamic programming

At the core of reinforcement learning is the derivation of an optimal policy; a function which calculates actions to be executed from a state. The reinforcement learning problem is suited to solving a framework framework of problems termed Markov Decision Processes (MDPs). These processes are characterised by five key parameters, S (state), A (action), P (transition matrix), R (reward) and \gamma (discount factor). If all five parameters are explicitly known, dynamic programming can be applied to MDPs to solve *(value) prediction* and *(optimal) control*. 

Dynamic programming provides a methodology to solve complex problems by breaking large/complex problems into smaller/more simple subproblems, solving subproblems and finally using subproblem solutions to construct solutions to the overall problem. Two important properties of dynamic programming: 

    1. Optimal substructure
    2. Overlapping subproblems
    
    1. Optimal substructure
    The idea of optimal substructure is premised on the idea complex problems can be decomposed into subproblems, calculate the optimal value for each subproblem then combine to form the overall optimal solution. 
    
    2. Overlapping subproblems
    Second, dynamic programming uses overlapping subproblems to cache solutions to previously calculated subproblems, store the output and reuse in calculations when the subproblems reoccur. 
    
    
Problems of the above form can be solved in both a prediction and control setting. Prediction solutions calculates the total value achievable from a state under a specific policy whereas control determines the action/decision that should be made in each state.



## Policy evaluation - prediction
Value of functions are a at the core of reinforcement learning.
Two value functions, state value functions - the utility for each particular state vs state-action value functions - the utility of taken a specific action from a state. Value functions have the structure of a Bellman equation, that is the value of the *current state*, $V(s)$, is equal to *immediate reward*, $R$, plus the value of *subsequent state* $V(s')$. Compactly the Bellman equation structure can be written as: 

\begin{align}
    V(s) &= R_t + V(s')
\end{align}

Through analysis of the Bellman equation the first important property of dyanmic programming, *optimal substructure* is immediately apparent. A state's value function is broken into two less complex problems - the *immediate reward* and the *value function* of the trajectory from next state.

Policy evaluation aims to solve the problem - "if I follow a particular policy $\pi$ calculate how 'good' is it to be in a particular state". State alue functions are used to calculate each values states. 

Value functions used to solve MDPs are a subtle difference between the dynamic programming solutions and complete reinforcement paradigm. 

An MDP and policy are given the policy is then evaluated as to how optimal it is. 

For dynamic programming, since transitions are known and do NOT have to be sampled the MDP can be solved be sweeping/updating all states in each iteration. Full reinforcement learning is different as the state transitions are not known; dynamics must be learnt from experiencing the environment. Under such condition only observed states are updated in each iteration NOT the entire state space as is the case with the complete MDP solution. 

Policy evaluation is covered in the following code: 
    1. Define imports and parameters
    2. Initialise state value function (matrix) - matrix of zeros
    3. Update state value function (matrix) - iteration by iteration

In [13]:
# 1. Define imports and parameters
from tkinter import *
import numpy as np
from dynamic_programming_helpers import *

CANVAS_HEIGHT_WIDTH = 600
GRID_DIM = 5
np.set_printoptions(suppress=True)

DISCOUNT_FACTOR = 1.0
REWARD = -1

line_distance = CANVAS_HEIGHT_WIDTH/GRID_DIM
label_offset = line_distance/2


#### Define policy
trans_prob = {"UP":0.25, "DOWN":0.25, "LEFT":0.25, "RIGHT":0.25}

In [6]:
# Initialise state value function
grid_values = np.zeros([GRID_DIM,GRID_DIM])
# Add edge of padding to simulate an edge node returning to state
grid_values = np.pad(grid_values,((1,1),(1,1)), mode='constant', constant_values=0)


grid_values = reset_goal_values(grid_values, goals_dim=[[1,1],[5,5]])


In [8]:
#iteration: 1
updated_grid_value = update_grid_state_value_function(grid_values, GRID_DIM, trans_prob, REWARD, DISCOUNT_FACTOR).round(2)

updated_grid_value = reset_state_values(updated_grid_value).round(2)

updated_grid_value = reset_goal_values(updated_grid_value, goals_dim=[[1,1],[5,5]]).round(2)
print(updated_grid_value)


[IN] column number 1 
[IN] column number 1 
[IN] column number 1 
[IN] column number 1 
[IN] column number 1 
[IN] column number 2 
[IN] column number 2 
[IN] column number 2 
[IN] column number 2 
[IN] column number 2 
[IN] column number 3 
[IN] column number 3 
[IN] column number 3 
[IN] column number 3 
[IN] column number 3 
[IN] column number 4 
[IN] column number 4 
[IN] column number 4 
[IN] column number 4 
[IN] column number 4 
[IN] column number 5 
[IN] column number 5 
[IN] column number 5 
[IN] column number 5 
[IN] column number 5 
[[-1. -1. -1. -1. -1. -1. -1.]
 [-1.  0. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  0. -1.]
 [-1. -1. -1. -1. -1. -1. -1.]]


In [ ]:
#iteration: 2
updated_grid_value = update_grid_state_value_function(updated_grid_value, GRID_DIM, trans_prob, REWARD, DISCOUNT_FACTOR).round(2)

updated_grid_value = reset_state_values(updated_grid_value).round(2)

updated_grid_value = reset_goal_values(updated_grid_value, goals_dim=[[1,1],[5,5]]).round(2)
print(updated_grid_value)

In [ ]:
#iteration: 3
updated_grid_value = update_grid_state_value_function(updated_grid_value, GRID_DIM, trans_prob, REWARD, DISCOUNT_FACTOR).round(2)

updated_grid_value = reset_state_values(updated_grid_value).round(2)

updated_grid_value = reset_goal_values(updated_grid_value, goals_dim=[[1,1],[5,5]]).round(2)
print(updated_grid_value)